services:
      db:
            image: mariadb
            restart: always
            environment:
                  MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
                  MARIADB_DATABASE: "${DB_DATABASE}"
                  MARIADB_USER: "${DB_USER}"
                  MARIADB_PASSWORD: "${DB_PASSWORD}"

      adminer:
            image: adminer
            restart: always
            ports:
                  - 8081:8080

      wordpress:
            image: wordpress:latest
            restart: always
            ports:
                  - 8080:80
            environment:
                  WORDPRESS_DB_HOST: db:3306
                  WORDPRESS_DB_NAME: "${DB_DATABASE}"
                  WORDPRESS_DB_USER: "${DB_USER}"
                  WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            volumes:
                  - wordpress_data:/var/www/html
                  - ./:/var/www/html/wp-content/plugins/sportlink.club.dataservices
                  - ./wp-themes:/var/www/html/wp-content/themes

      wpcli:
            image: wordpress:cli
            depends_on:
                  - wordpress
                  - db
            environment:
                  WORDPRESS_DB_HOST: db:3306
                  WORDPRESS_DB_NAME: "${DB_DATABASE}"
                  WORDPRESS_DB_USER: "${DB_USER}"
                  WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
                  WP_SITE_URL: "${WP_SITE_URL}"
                  WP_SITE_TITLE: "${WP_SITE_TITLE}"
                  WP_ADMIN_USER: "${WP_ADMIN_USER}"
                  WP_ADMIN_PASSWORD: "${WP_ADMIN_PASSWORD}"
                  WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL}"
                  SPORTLINK_API_KEY: "${SPORTLINK_API_KEY}"
                  SPORTLINK_CACHE_TIME: "${SPORTLINK_CACHE_TIME}"
            volumes:
                  - wordpress_data:/var/www/html
                  - ./:/var/www/html/wp-content/plugins/sportlink.club.dataservices
                  - ./wp-themes:/var/www/html/wp-content/themes
                  - ./wp-install.sh:/usr/local/bin/wp-install.sh
            entrypoint: sh /usr/local/bin/wp-install.sh
            command: tail -f /dev/null

volumes:
      wordpress_data:
