version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USER}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${DB_DATABASE}'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./:/var/www/html/wp-content/plugins/sportlink.club.dataservices
      - ./wp-themes:/var/www/html/wp-content/themes
